# **$$Word2Vec$$**

In [11]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/googlenewsvectorsnegative300/GoogleNews-vectors-negative300.bin.gz
/kaggle/input/googlenewsvectorsnegative300/GoogleNews-vectors-negative300.bin


In [12]:
import gensim
from gensim.models import Word2Vec, KeyedVectors

In [13]:
path = "/kaggle/input/googlenewsvectorsnegative300/GoogleNews-vectors-negative300.bin"
model = KeyedVectors.load_word2vec_format(path, binary=True, limit=500000)

In [15]:
model['man']

array([ 0.32617188,  0.13085938,  0.03466797, -0.08300781,  0.08984375,
       -0.04125977, -0.19824219,  0.00689697,  0.14355469,  0.0019455 ,
        0.02880859, -0.25      , -0.08398438, -0.15136719, -0.10205078,
        0.04077148, -0.09765625,  0.05932617,  0.02978516, -0.10058594,
       -0.13085938,  0.001297  ,  0.02612305, -0.27148438,  0.06396484,
       -0.19140625, -0.078125  ,  0.25976562,  0.375     , -0.04541016,
        0.16210938,  0.13671875, -0.06396484, -0.02062988, -0.09667969,
        0.25390625,  0.24804688, -0.12695312,  0.07177734,  0.3203125 ,
        0.03149414, -0.03857422,  0.21191406, -0.00811768,  0.22265625,
       -0.13476562, -0.07617188,  0.01049805, -0.05175781,  0.03808594,
       -0.13378906,  0.125     ,  0.0559082 , -0.18261719,  0.08154297,
       -0.08447266, -0.07763672, -0.04345703,  0.08105469, -0.01092529,
        0.17480469,  0.30664062, -0.04321289, -0.01416016,  0.09082031,
       -0.00927734, -0.03442383, -0.11523438,  0.12451172, -0.02

In [16]:
model['Cricket']

array([-3.80859375e-01, -1.44531250e-01,  3.02734375e-01, -2.11914062e-01,
       -1.74804688e-01,  4.24804688e-02,  2.53906250e-01, -2.04101562e-01,
       -8.93554688e-02,  2.75878906e-02,  9.81445312e-02, -2.71484375e-01,
       -1.62353516e-02,  1.68945312e-01,  2.55859375e-01,  2.70996094e-02,
        6.98242188e-02,  1.34765625e-01,  7.81250000e-02,  1.95312500e-01,
       -8.53538513e-05, -3.17382812e-02,  7.12890625e-02, -5.00000000e-01,
        3.78906250e-01,  1.36718750e-01,  4.83398438e-02,  5.11718750e-01,
        6.52343750e-01, -1.94335938e-01, -2.01171875e-01,  9.71679688e-02,
       -3.55468750e-01,  1.28173828e-02,  4.80957031e-02,  7.56835938e-02,
       -2.91015625e-01, -3.24707031e-02,  2.09960938e-02, -1.23535156e-01,
        1.91650391e-02, -5.27343750e-02,  2.26562500e-01,  1.01562500e-01,
       -8.15429688e-02, -3.12500000e-01,  1.46484375e-01, -3.24218750e-01,
        4.22363281e-02,  1.91406250e-01, -1.64062500e-01,  1.96289062e-01,
        2.26562500e-01,  

In [17]:
model.most_similar('man')

[('woman', 0.7664012908935547),
 ('boy', 0.6824870705604553),
 ('teenager', 0.6586930155754089),
 ('teenage_girl', 0.6147903203964233),
 ('girl', 0.5921714305877686),
 ('robber', 0.5585119128227234),
 ('Robbery_suspect', 0.5584409832954407),
 ('teen_ager', 0.5549197196960449),
 ('men', 0.5489763021469116),
 ('guy', 0.5420035719871521)]

In [24]:
model.most_similar('women')

[('men', 0.767493724822998),
 ('Women', 0.7283449172973633),
 ('womens', 0.6786180734634399),
 ('girls', 0.6339040398597717),
 ('females', 0.6240420341491699),
 ('mothers', 0.6050934195518494),
 ('ladies', 0.5865179300308228),
 ('husbands', 0.5705341696739197),
 ('Men', 0.5693342089653015),
 ('female', 0.5556280612945557)]

In [21]:
model.similarity('man', 'women')

0.28830528

In [25]:
model.similarity('women', 'female')

0.5556281

In [26]:
model.similarity('laptop','computer')

0.66404927

In [27]:
model.doesnt_match(['PHP','java','monkey'])

'monkey'

In [29]:
vec = model['king']- model['man'] + model['women']
vec

array([-0.33984375,  0.06298828, -0.00994873,  0.3305664 ,  0.10327148,
       -0.25854492,  0.19677734, -0.32476807, -0.15917969,  0.45752716,
       -0.39208984, -0.22460938,  0.02929688,  0.31982422, -0.0958252 ,
       -0.05932617,  0.01855469, -0.03945923,  0.01101685,  0.33984375,
        0.10351562,  0.14396667, -0.07641602,  0.06640625, -0.10839844,
       -0.1953125 , -0.3564453 , -0.02124023, -0.16503906, -0.16247559,
       -0.05519104, -0.1003418 ,  0.01464844,  0.23449707, -0.26611328,
       -0.07080078, -0.26904297, -0.00292969, -0.06738281, -0.02050781,
        0.04418945, -0.09326172,  0.12304688,  0.10626221,  0.10290527,
        0.01660156, -0.10791016, -0.0065918 ,  0.17578125,  0.10028076,
        0.22363281, -0.05761719, -0.31743622,  0.3922119 , -0.35498047,
       -0.23643494, -0.01074219, -0.01334572, -0.15283203, -0.00793457,
        0.08203125,  0.09985352,  0.003479  ,  0.11608887,  0.14550781,
       -0.125     , -0.11254883,  0.2548828 , -0.04345703,  0.34

In [30]:
model.most_similar([vec])

[('king', 0.6478992104530334),
 ('queen', 0.5354938507080078),
 ('women', 0.52336585521698),
 ('kings', 0.5162314772605896),
 ('queens', 0.499536395072937),
 ('princes', 0.46233269572257996),
 ('monarch', 0.45280295610427856),
 ('monarchy', 0.4293173849582672),
 ('crown_prince', 0.42302513122558594),
 ('concubines', 0.4224807024002075)]

In [31]:
vec = model['INR'] - model ['India'] + model['England']
model.most_similar([vec])

[('INR', 0.6442340612411499),
 ('GBP', 0.5040826201438904),
 ('England', 0.44649264216423035),
 ('£', 0.43340998888015747),
 ('Â_£', 0.4307197630405426),
 ('£_#.##m', 0.42561301589012146),
 ('Pounds_Sterling', 0.42512619495391846),
 ('GBP##', 0.42464491724967957),
 ('stg', 0.42324796319007874),
 ('£_#.###m', 0.4201711118221283)]